version: '2'
services:
  nginx:
    image: labhackercd/nginx-edemocracia
    depends_on:
     - colab
    volumes:
     - colab_assets:/var/labhacker/colab/public:z
     - audiencias:/var/labhacker/audiencias:z
     - wikilegis:/var/labhacker/wikilegis:z
    ports:
     - "8000:80"
    links:
     - 'audienciasweb'
    environment:
      NAME_RESOLVER: '127.0.0.11'
 
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
      PGDATA : /var/lib/postgresql/data/
    volumes:
     - pg_data:/var/lib/postgresql/data/
 
  colab:
    image: labhackercd/edemocracia-colab:1.15.5
    command: ./start-colab.sh
    environment: # Variáveis de ambiente
      # Settings da aplicação
      DEBUG: 'True' # Se 'True' mostra os erros da aplicação na página.
      TEMPLATE_DEBUG: 'True' # Se 'True', mostra os erros de template.
      SECRET_KEY: 'secret' # Chave usada para maioria das funções de criptografia
      ALLOWED_HOSTS: '*' # Lista de hosts permitidos para acessar a aplicação
      ROBOTS_NOINDEX: "True" # Se 'True', orienta os buscadores a não indexar o conteúdo da página e impede-a de seguir os links para descobrir novas páginas.
      # Configuração de conta de email para aplicação
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia" <edemocracia@camara.leg.br>'
      SERVER_EMAIL: ''
      EMAIL_HOST: ''
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_TLS: ''
      EMAIL_SUBJECT_PREFIX: '[e-Democracia]'
      # Configuração de plugins externos
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: '' # Id do app google para login social
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: '' # Chave do app google para login social
      SOCIAL_AUTH_FACEBOOK_KEY: '' # Id do app facebook para login social
      SOCIAL_AUTH_FACEBOOK_SECRET: '' # Chave do app facebook para login social
      RECAPTCHA_SITE_KEY: '' # Id do app google-recaptcha para formulário de cadastro
      RECAPTCHA_PRIVATE_KEY: '' # Chave do app google-recaptcha para formulário de cadastro
      # Configuração do banco de dados
      DATABASE_HOST: 'db'
      DATABASE_NAME: 'colab'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'root'
      MEMCACHED_LOCATION: 'memcached:1234' # Endereço usado para guardar os dados em CACHE
      # Credenciais para criar um superusuário padrão 
      ADMIN_EMAIL: email@admin.com
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: 123
      # Configurações de customização
      SITE_DOMAIN: http://127.0.0.1:8000 # Endereço do site, usado para montar os links da aplicação
      SITE_NAME: Câmara dos Deputados # Título do site, aparece na página inicial
      SITE_LOGO: '' # Altera a imagem em destaque no header da página inicial
      ENABLE_AUDIENCIAS: 'false' # Habilita a ferramenta Audiências Interativas e adiciona na página inicial
      ENABLE_WIKILEGIS: 'false' # Habilita a ferramenta Wikilegis e adiciona na página inicial
      AUDIENCIAS_API_KEY: secret_key # Chave da API do Audiências para ter acesso total a API. 
      WIKILEGIS_API_KEY: api_key # Chave da API do Wikilegis para ter acesso total a API. 
    volumes:
     - colab_assets:/var/labhacker/colab/public:z
    links:
     - 'audienciasweb'
    expose:
     - "8000"
    depends_on:
     - db
 
  redis:
    image: redis:alpine
 
  audienciasweb:
    image: labhackercd/audiencias-publicas:1.2.1
    command: ./start-web.sh
    restart: on-failure
    links:
     - db
     - redis
    volumes:
     - audiencias:/var/labhacker/audiencias
    environment: # Variáveis de ambiente
      # Configuração de conta de email
      EMAIL_HOST: ''
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_PORT: 25
      EMAIL_USE_TLS: 'False'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[audiencias]" <edemocracia@camara.leg.br>'
      NOTIFICATION_EMAIL_LIST: '' # Lista de emails que serão notificados ao criar uma nova sala
      # Configuração de aplicação
      DJANGO_SECRET_KEY: secret_key #  Chave usada para maioria das funções de criptografia
      DEBUG: 'False' # Se 'True' mostra os erros da aplicação na página.
      ENABLE_REMOTE_USER: 'True' # Habilita a criação de usuário pelo colab
      URL_PREFIX: audiencias # Adiciona um prefixo nas urls
      FORCE_SCRIPT_NAME: /audiencias # Força o path ao endereço do domínio
      STATIC_URL: /audiencias/static/ # Caminho dos arquivos estáticos
      SESSION_COOKIE_NAME: audiencias_session # nome da seção criado no navegador
      LOGIN_URL: /home # Endereço para login
      LOGIN_REDIRECT_URL: /home # Endereço de redirecionamento após login
      LOGOUT_REDIRECT_URL: /home # Endereço de redirecionamento após logout
      ALLOWED_HOSTS: 'audienciasweb, 127.0.0.1' # Lista de hosts permitidos para acessar a aplicação
      COMPRESS_OFFLINE: 'True' # Se 'True', faz a compressão de arquivos fora do loop de solicitação/resposta
      # Configuração de plugins terceiros
      GOOGLE_ANALYTICS_ID: '' # Id do app do google analytics para monitorar o acesso
      OLARK_ID: '' # id do app Olark para "chat online" e "fale conosco"
      WEBSERVICE_URL: '' # Endereço do webservice com os dados do amdamento das salas
      # Credenciais para criar um superusuário padrão 
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: email@admin.com
      ADMIN_USERNAME: admin
      # Configuração do banco de dados
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: audiencias
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_SERVER: redis
      # Configuração de customização
      SITE_DOMAIN: http://127.0.0.1:8000 # Endereço do site, usado para montar os links da aplicação
      SITE_NAME: Câmara dos Deputados # Título do site, aparece na barra superior.
    expose:
     - "8000"
    depends_on:
     - db
     - redis
 
  audienciasworker:
    image: labhackercd/audiencias-publicas:1.2.1
    command: ./start-worker.sh
    links:
     - redis
     - db
    environment: # Variáveis de ambiente
      # Configuração de conta de email
      EMAIL_HOST: ''
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_PORT: 25
      EMAIL_USE_TLS: 'False'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[audiencias]" <edemocracia@camara.leg.br>'
      NOTIFICATION_EMAIL_LIST: '' # Lista de emails que serão notificados ao criar uma nova sala
      # Configuração de aplicação
      DJANGO_SECRET_KEY: secret_key # Chave usada para maioria das funções de criptografia
      DEBUG: 'False' # Se 'True' mostra os erros da aplicação na página.
      ENABLE_REMOTE_USER: 'True' # Habilita a criação de usuário pelo colab
      URL_PREFIX: audiencias # Adiciona um prefixo nas urls
      FORCE_SCRIPT_NAME: /audiencias # Força o path ao endereço do domínio
      STATIC_URL: /audiencias/static/ # Caminho dos arquivos estáticos
      SESSION_COOKIE_NAME: audiencias_session # nome da seção criado no navegador
      LOGIN_URL: /home # Endereço para login
      LOGIN_REDIRECT_URL: /home # Endereço de redirecionamento após login
      LOGOUT_REDIRECT_URL: /home # Endereço de redirecionamento após logout
      ALLOWED_HOSTS: 'audienciasweb, 127.0.0.1' # Lista de hosts permitidos para acessar a aplicação
      COMPRESS_OFFLINE: 'True' # Se 'True', faz a compressão de arquivos fora do loop de solicitação/resposta
      # Configuração de plugins terceiros
      GOOGLE_ANALYTICS_ID: '' # Id do app do google analytics para monitorar o acesso
      OLARK_ID: '' # id do app Olark para "chat online" e "fale conosco"
      WEBSERVICE_URL: '' # Endereço do webservice com os dados do amdamento das salas
      # Credenciais para criar um superusuário padrão 
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: email@admin.com
      ADMIN_USERNAME: admin
      # Configuração do banco de dados
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: audiencias
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_SERVER: redis
      # Configuração de customização
      SITE_DOMAIN: http://127.0.0.1:8000 # Endereço do site, usado para montar os links da aplicação
      SITE_NAME: Câmara dos Deputados # Título do site, aparece na barra superior.
    volumes:
     - audiencias:/var/labhacker/audiencias
    depends_on:
     - 'audienciasweb'
 
  wikilegisweb:
    image: labhackercd/wikilegis:1.3.3
    command: ./start.sh
    restart: on-failure
    links:
     - db
    volumes:
     - wikilegis:/var/labhacker/wikilegis
    environment: # Variáveis de ambiente
      # Configuração de aplicação
      API_KEY: api_key # Chave da API para conceder acesso total. 
      SECRET_KEY: secret_key # Chave usada para maioria das funções de criptografia
      FORCE_SCRIPT_NAME: /wikilegis # Força o path ao endereço do domínio
      DEBUG: 'False' # Se 'True' mostra os erros da aplicação na página.
      ALLOWED_HOSTS: '*' # Lista de hosts permitidos para acessar a aplicação
      LOGIN_URL: /home # Endereço para login
      LOGIN_REDIRECT_URL: / # Endereço de redirecionamento após login
      AUTH_USER_MODEL: accounts.User # Especifica qual modelo de usuário será usado pelo sistema
      ENABLE_REMOTE_USER: 'True' # Habilita a criação de usuário pelo colab
      SESSION_COOKIE_NAME: wikilegis_session # nome da seção criado no navegador
      ACCOUNT_ACTIVATION_REQUIRED: 0 # Habilita ativação de conta por email se ENABLE_REMOTE_USER for 'False'
      ACCOUNT_ACTIVATION_DAYS: 7 # Define o tempo em dias em que o codigo de ativação estará funcionando se ENABLE_REMOTE_USER for 'False'
      ENABLE_SOCIAL_AUTH: 'False' # Se 'True', habilita login social se ENABLE_REMOTE_USER for 'False'
      LANGUAGE_CODE: pt-br # Define o idioma
      TIME_ZONE: America/Sao_Paulo # Define o o fuso horário
      STATIC_URL: /wikilegis/static/ # Caminho para arquivos estáticos
      MEDIA_URL: /wikilegis/media/ # Caminho para arquivos de midia
      COMPRESS_OFFLINE: 'True' # Se 'True', faz a compressão de arquivos fora do loop de solicitação/resposta
      # Configuração de conta de email
      EMAIL_HOST: ''
      EMAIL_PORT: 25
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_TLS: 'False'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[Wikilegis]" <edemocracia@camara.leg.br>'
      # Credenciais para criar um superusuário padrão
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: email@admin.com
      # Configuração do banco de dados
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: wikilegis
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      # Configuração de customização
      SITE_DOMAIN: http://127.0.0.1:8000 # Endereço do site, usado para montar os links da aplicação
      SITE_NAME: Câmara dos Deputados # Título do site, aparece na barra superior.
    expose:
     - "8000"
    depends_on:
     - db
 
volumes:
  pg_data:
    driver: local
  colab_assets:
    driver: local
  audiencias:
    driver: local
  wikilegis:
    driver: local